language: sql
# blacklist
branches:
  except:
    - master

env:
  - DB=db2
  - DB=postgres

before_install:
  - pwd
  - df -h

  # DB2
  # Install the required libraries
  - sudo apt-get update -qq
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get -y install ksh curl aria2 numactl ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get -y install rpm binutils libaio1 lib32stdc++6 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get install -qq libpam-ldap:i386 ; fi"
  #libstdc++6-4.4-pic libstdc++6-4.4-dev libstdc++5 rpm
  - sh -c "if [ '$DB' = 'db2' ]; then sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0 ; fi"
    # Retrieves and extracts the DB2 binaries
  - cd /tmp
  - sh -c "if [ '$DB' = 'db2' ]; then curl --url https://raw.githubusercontent.com/wiki/angoca/BenchmarkSQL/DB2-Download-link.md -s > link ; cat link | tail -1 > link2 ; cat link2 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then aria2c -x 16 $(cat link2) ; tar zvxf v*_linuxx64_expc.tar.gz ; fi"
  # Checks the prerequisites
  - sh -c "if [ '$DB' = 'db2' ]; then server_t/db2prereqcheck -i -l; fi"
  # Install DB2 and creates an instance (Response file)
  - sh -c "if [ '$DB' = 'db2' ]; then sudo server_t/db2setup -r ${TRAVIS_BUILD_DIR}/run/db2expc.rsp || cat /tmp/db2setup.log ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then echo \"db2admin\\\ndb2admin\" | sudo passwd db2inst1 ; fi"
  # Creates the database
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c \"db2 create db bmarkdb\" ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c \"db2 connect to bmarkdb ; db2 grant dbadm on database to user ${USER}\" ; fi"
  # Modifies the scripts
  - cd
  - cd build/angoca/BenchmarkSQL/run
  - sh -c "if [ '$DB' = 'db2' ]; then sed 's/^myCP=\"\.\./myCP=\"\/opt\/ibm\/db2\/V*\/java\/db2jcc4\.jar:\.\./g' runSQL.sh > runSQL2.sh; mv runSQL2.sh runSQL.sh; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sed 's/-cp \.:/-cp \.:\/opt\/ibm\/db2\/V*.5\/java\/db2jcc4\.jar:/g' runBenchmark.sh > runBenchmark2.sh; mv runBenchmark2.sh runBenchmark.sh; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sed 's/-cp \.:/-cp \.:\/opt\/ibm\/db2\/V*\/java\/db2jcc4\.jar:/g' runLoader.sh > runLoader2.sh; mv runLoader2.sh runLoader.sh; fi"

  # Postgres
  - sh -c "if [ '$DB' = 'postgres' ]; then sudo -u postgres psql -c \"create user benchmarksql with superuser password 'password'\"; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then sudo -u postgres psql -c \"grant all privileges on database postgres to benchmarksql\"; fi"

  - cat run*.sh
  - chmod +x run*.sh
  - df -h
  - df -ih

install:
  # DB2
  - sh -c "if [ '$DB' = 'db2' ]; then ./runSQL.sh props.db2 sqlTableCreates_DB2; fi"
  # Postgres
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runSQL.sh props.pg sqlTableCreates; fi"
  - df -h

script:
  - sh -c "if [ '$DB' = 'db2' ]; then ./runLoader.sh props.db2 numWarehouses 1; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then ./runSQL.sh props.db2 sqlIndexCreates_DB2; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then ./runBenchmark.sh props.db2; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runLoader.sh props.pg numWarehouses 1; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runSQL.sh props.pg sqlIndexCreates; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runBenchmark.sh props.pg; fi"

after_script:
  - df -h
  - df -ih
  - cat log/BenchmarkSQLError.log
  - cat log/benchmarksql.log

